# General settings
[general]
filesystem_size = 1024 # give it more space
prompt = false

# Package settings
[packages]
kernel = {}
redoxfs = {}
drivers = {}
bootloader = {}

[[files]]
path = "/etc/hostname"
data = "redox-rpi5"

[[files]]
path = "/dev/tty"
data = "uart:"
